### Site Settings ###
title: ErickQian
description: >- 
  Just do it.
baseurl: ""
url: "" 
repository: ErickQian/ErickQian.github.io
archive_dir: archive
tag_dir: tags
category_dir: categories

# Build settings
markdown: kramdown

### Plugins ###
plugins:
  - jekyll-feed


### Author Info ###
author:
  name              : ErickQian
  image             : https://i.postimg.cc/fTRGGjdr/hd-imag01.jpg
  email             : qianyunkang@gmail.com
  github            : ErickQian
# twitter           : 
# linkedin          : 
# facebook          : 
# dribbble          : your_username
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username

comments:
  provider: gitalk # "disqus", "gitalk", "valine"
  ## Disqus
  disqus:
    shortname: https-qianyunkang-github-io # the Disqus shortname for the site

  ### Gitalk ###
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : e0712dde20ba0da59c33 # GitHub Application Client ID
    clientSecret: 24dc17828d8ebc9f78c7b427597d019afc239336 # GitHub Application Client Secret
    repository  : ErickQian.github.io # GitHub repo
    owner       : ErickQian # GitHub repo owner
    admin: ErickQian # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.

  ### Valine ###
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : nvKhhaSS9ecf2X8yEeMgeJhG-gzGzoHsz # LeanCloud App id
    app_key     : xGBXXtpdHAJBmigEUOLCmhBV # LeanCloud App key
    placeholder : 评论 # Prompt information

### page view ###
pageview:
  provider: leancloud
  leancloud:
    app_id    : DeAb9qzrQbDK3VApHPKCAbk1-9Nh9j0Va
    app_key   : RWtJMvC3zFhNeDGCUcXrCXLw
    app_class : Blog_Views

#### Analytics ###
analytics:
  # google
  provider: google 

  # Google Analytics
  google:
    # Google Analytics id for the site
    tracking_id : UA-122466435-1


### Sharing ###
sharing:
  provider: addtoany # "addtoany"

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock